### ISSUE TITLE
Code doesn't compile on Rust 1.86

### ISSUE THREAD

**Issue by afilini** [PortalTechnologiesInc/healthcheck-service#2]
```
nixos-website | error[E0658]: `let` expressions in this position are unstable
nixos-website |    --> src/main.rs:380:12
nixos-website |     |
nixos-website | 380 |         if let Some(message_id) = existing_message_id
nixos-website |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nixos-website |     |
nixos-website |     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
nixos-website | 
nixos-website | error[E0658]: `let` expressions in this position are unstable
nixos-website |   --> src/storage.rs:21:12
nixos-website |    |
nixos-website | 21 |         if let Some(parent) = path.parent()
nixos-website |    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nixos-website |    |
nixos-website |    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
```
